#!/bin/bash
# RAGFlow Quick-Start: Upload Manuscript Files
# This script helps you organize files for upload to RAGFlow

echo "==================================================================="
echo "RAGFlow Quick-Start for BCC Manuscript Refinement"
echo "==================================================================="
echo ""
echo "RAGFlow is running at: http://localhost"
echo ""
echo "STEP 1: Login to RAGFlow and create 3 Knowledge Bases:"
echo "  - KB1: 'BCC Manuscript' (your work)"
echo "  - KB2: 'Reference Literature' (PDFs of papers)"
echo "  - KB3: 'Code & Methods' (Python code, notebooks)"
echo ""
echo "==================================================================="
echo "STEP 2: Upload files to each Knowledge Base"
echo "==================================================================="
echo ""

# KB1: BCC Manuscript
echo "📚 KB1: 'BCC Manuscript' - Upload these files:"
echo "-------------------------------------------------------------------"
echo ""
echo "Main Manuscript:"
echo "  /Users/mac/LIFE/life/manuscript/main_countercurvature_refined.tex"
echo ""
echo "Manuscript Sections (all 12):"
echo "  /Users/mac/LIFE/life/manuscript/sections/abstract.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/introduction.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/theory.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/methods.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/results.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/discussion.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/conclusion.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/significance.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/availability.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/countercurvature_metric.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/longevity_methods.tex"
echo "  /Users/mac/LIFE/life/manuscript/sections/fig_captions.tex"
echo ""
echo "Draft Files:"
echo "  /Users/mac/LIFE/draft_intro_BCC.md"
echo "  /Users/mac/LIFE/draft_theory_BCC.md"
echo "  /Users/mac/LIFE/draft_methods_BCC.md"
echo "  /Users/mac/LIFE/draft_results_BCC.md"
echo "  /Users/mac/LIFE/draft_discussion_BCC.md"
echo "  /Users/mac/LIFE/draft_conclusion_BCC.md"
echo ""
echo "Planning Documents:"
echo "  /Users/mac/LIFE/ABSTRACT_TITLE_OPTIONS_BCC.md"
echo "  /Users/mac/LIFE/TARGET_OUTLINE_BCC.md"
echo "  /Users/mac/LIFE/MANUSCRIPT_PLAN_BCC.md"
echo "  /Users/mac/LIFE/MANUSCRIPT_PLAN_BCC_INSTELLA.md"
echo ""
echo "Bibliography:"
echo "  /Users/mac/LIFE/life/manuscript/refs.bib"
echo ""
echo "==================================================================="
echo ""

# KB2: Reference Literature
echo "📖 KB2: 'Reference Literature' - Upload PDFs of papers on:"
echo "-------------------------------------------------------------------"
echo "  - Cosserat rod mechanics"
echo "  - Developmental biology (HOX/PAX genes)"
echo "  - Spinal biomechanics"
echo "  - Scoliosis research"
echo "  - Information theory in biology"
echo "  - Differential geometry / General Relativity (for metric analogy)"
echo ""
echo "NOTE: You'll need to manually add your PDF files to this KB"
echo ""
echo "==================================================================="
echo ""

# KB3: Code & Methods
echo "💻 KB3: 'Code & Methods' - Upload code and notebooks:"
echo "-------------------------------------------------------------------"
echo "  - Python scripts from /Users/mac/LIFE/life/src/spinalmodes/"
echo "  - Jupyter notebooks"
echo "  - Experiment scripts"
echo "  - Figure generation code"
echo ""
echo "NOTE: Upload relevant Python files and notebooks manually"
echo ""
echo "==================================================================="
echo ""

echo "STEP 3: Start with these quick wins:"
echo "-------------------------------------------------------------------"
echo ""
echo "1. Use Case 2: Consistency Checking"
echo "   Query: 'How is Information-Elasticity Coupling (IEC) defined"
echo "          in different sections?'"
echo ""
echo "2. Use Case 8: Figure-Text Alignment"
echo "   Query: 'Where is Figure 3 first mentioned in the text?'"
echo ""
echo "3. Use Case 3: Theoretical Validation"
echo "   Query: 'Is there an explicit energy density equation in the"
echo "          theory section?'"
echo ""
echo "==================================================================="
echo ""
echo "📖 Full guide available at:"
echo "   /Users/mac/.gemini/antigravity/brain/4100bd87-456e-4a79-895a-8073323d4d18/ragflow_research_guide.md"
echo ""
echo "🚀 Ready to refine your research!"
echo "==================================================================="
