#!/usr/bin/env python3
"""
run_afcc_daily_pipeline.py

Orchestrates the daily AlphaFold Counter-Curvature (AFCC) pipeline cycle.
1. Prepares candidates.
2. Fetches structures.
3. Computes metrics.
4. Generates reports.
5. Archives results to versioned outputs.
6. Updates dashboard.
"""

import sys
import shutil
import datetime
import subprocess
from pathlib import Path
import pandas as pd

# Define paths
REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
AFCC_DIR = REPO_ROOT / "research" / "alphafold_countercurvature"
SCRIPTS_DIR = AFCC_DIR / "scripts"
DATA_PROCESSED_DIR = AFCC_DIR / "data" / "processed"
OUTPUTS_DIR = REPO_ROOT / "outputs" / "afcc"
DASHBOARD_FILE = REPO_ROOT / "reports" / "afcc_latest.md"

def run_command(command, description):
    print(f"\n🚀 {description}...")
    try:
        subprocess.check_call(command, cwd=REPO_ROOT)
        print(f"✅ {description} complete.")
        return True
    except subprocess.CalledProcessError as e:
        print(f"❌ {description} failed with exit code {e.returncode}.")
        return False

def main():
    today_str = datetime.datetime.now().strftime("%Y-%m-%d")
    daily_output_dir = OUTPUTS_DIR / today_str
    daily_output_dir.mkdir(parents=True, exist_ok=True)

    failure_log = daily_output_dir / "failure.md"

    print(f"Starting AFCC Daily Pipeline for {today_str}")

    # 1. Prepare Candidates
    cmd_prep = [sys.executable, str(SCRIPTS_DIR / "prepare_daily_run.py")]
    if not run_command(cmd_prep, "Preparing Daily Candidates"):
        with open(failure_log, "w") as f:
            f.write(f"# Failure Report {today_str}\n\nFailed at step: Prepare Daily Candidates")
        sys.exit(1)

    # 2. Fetch Structures
    # Note: 02_fetch_afdb.py uses uniprot_mapping.csv generated by prep step
    cmd_fetch = [sys.executable, str(SCRIPTS_DIR / "02_fetch_afdb.py")]
    if not run_command(cmd_fetch, "Fetching AlphaFold Structures"):
         with open(failure_log, "w") as f:
            f.write(f"# Failure Report {today_str}\n\nFailed at step: Fetch AlphaFold Structures")
         # We might continue even if some fetch failed, but if script errored out, maybe stop.
         # The script handles partial failures, but if it crashes, we stop.
         sys.exit(1)

    # 3. Compute Metrics
    cmd_metrics = [sys.executable, str(SCRIPTS_DIR / "04_analyze_metrics.py")]
    if not run_command(cmd_metrics, "Analyzing Metrics"):
        with open(failure_log, "w") as f:
            f.write(f"# Failure Report {today_str}\n\nFailed at step: Analyze Metrics")
        sys.exit(1)

    # 4. Generate Bolt Report
    cmd_report = [sys.executable, str(SCRIPTS_DIR / "06_bolt_report.py")]
    if not run_command(cmd_report, "Generating Bolt Report"):
        with open(failure_log, "w") as f:
            f.write(f"# Failure Report {today_str}\n\nFailed at step: Generate Bolt Report")
        sys.exit(1)

    # 5. Archive Outputs
    print(f"\n📦 Archiving outputs to {daily_output_dir}...")

    src_metrics = DATA_PROCESSED_DIR / "protein_metrics.csv"
    dst_metrics = daily_output_dir / "metrics.csv"

    src_summary = DATA_PROCESSED_DIR / "bolt_biofold_results.md"
    dst_summary = daily_output_dir / "summary.md"

    src_figures = DATA_PROCESSED_DIR / "figures"
    dst_figures = daily_output_dir / "figures"

    if src_metrics.exists():
        shutil.copy(src_metrics, dst_metrics)
        print(f"   Saved {dst_metrics}")
    else:
        print(f"⚠️  Missing {src_metrics}")

    if src_summary.exists():
        shutil.copy(src_summary, dst_summary)
        print(f"   Saved {dst_summary}")
    else:
        print(f"⚠️  Missing {src_summary}")

    # Copy figures if they exist
    if src_figures.exists():
        if dst_figures.exists():
            shutil.rmtree(dst_figures)
        shutil.copytree(src_figures, dst_figures)
        print(f"   Saved figures to {dst_figures}")
    else:
        print(f"⚠️  Missing figures directory {src_figures}")

    # 6. Update Dashboard
    print(f"\n📊 Updating Dashboard at {DASHBOARD_FILE}...")

    try:
        # Load metrics to find top candidates
        df = pd.read_csv(src_metrics)

        # Identify top anisotropy
        # Legacy column check
        aniso_col = 'anisotropy_index' if 'anisotropy_index' in df.columns else 'anisotropy'
        plddt_col = 'plddt_mean' if 'plddt_mean' in df.columns else 'mean_plddt'

        top_aniso = df.sort_values(by=aniso_col, ascending=False).head(3)

        # Prepare content
        update_text = f"\n\n## {today_str}: Daily Refresh\n\n"
        update_text += "**Summary:**\n"
        update_text += f"- **Processed:** {len(df)} structures.\n"

        if not top_aniso.empty:
            best = top_aniso.iloc[0]
            update_text += f"- **Top Candidate:** **{best['gene_symbol']}** (Anisotropy: {best[aniso_col]:.2f})\n"

        update_text += "\n**Top 3 High Anisotropy:**\n"
        for _, row in top_aniso.iterrows():
            update_text += f"- **{row['gene_symbol']}**: Aniso={row[aniso_col]:.2f}, pLDDT={row[plddt_col]:.1f}\n"

        update_text += f"\n**Outputs:**\n"
        update_text += f"- [Metrics CSV](outputs/afcc/{today_str}/metrics.csv)\n"
        update_text += f"- [Summary Report](outputs/afcc/{today_str}/summary.md)\n"

        with open(DASHBOARD_FILE, "a") as f:
            f.write(update_text)

        print("✅ Dashboard updated.")

    except Exception as e:
        print(f"⚠️  Failed to update dashboard: {e}")
        with open(failure_log, "a") as f:
            f.write(f"\nFailed to update dashboard: {e}")

    print("\n✨ Daily Cycle Complete.")

if __name__ == "__main__":
    main()
