import pandas as pd
from pathlib import Path
from datetime import datetime

def main():
    metrics_file_path = 'outputs/afcc/2026-02-16/metrics.csv'
    metrics_file = Path(metrics_file_path)
    if not metrics_file.exists():
        print(f"Error: {metrics_file} does not exist.")
        return

    df = pd.read_csv(metrics_file)

    # Make sure we have the necessary columns
    required_cols = ['gene_symbol', 'anisotropy_index', 'pLDDT_mean', 'PAE_domain_blockiness_score', 'morphology']
    for col in required_cols:
        if col not in df.columns:
            if col == 'pLDDT_mean' and 'plddt_mean' in df.columns:
                df.rename(columns={'plddt_mean': 'pLDDT_mean'}, inplace=True)
            else:
                print(f"Error: Column {col} missing from data.")
                return

    # Filter and sort
    # High anisotropy + adequate confidence
    high_conf = df[(df['anisotropy_index'] >= 3.0) & (df['pLDDT_mean'] >= 70)].copy()
    high_conf['Confidence_Tier'] = 'High_Anisotropy_Adequate_Confidence'
    high_conf = high_conf.sort_values(by='anisotropy_index', ascending=False)

    # High anisotropy + low confidence
    low_conf = df[(df['anisotropy_index'] >= 3.0) & (df['pLDDT_mean'] < 70)].copy()
    low_conf['Confidence_Tier'] = 'High_Anisotropy_Low_Confidence'
    low_conf = low_conf.sort_values(by='anisotropy_index', ascending=False)

    # Combine and sort by confidence tier then anisotropy
    combined = pd.concat([high_conf, low_conf])

    # Let's also add the LBX1 comparator panel specifically requested
    panel_genes = ['LBX1', 'PIEZO2', 'LMNA', 'ADGRG6', 'RUNX3', 'POC5', 'GHR']
    panel_df = df[df['gene_symbol'].isin(panel_genes)].copy()
    panel_df['Confidence_Tier'] = 'Comparator_Panel'

    # Combine all
    final_df = pd.concat([combined, panel_df]).drop_duplicates(subset=['gene_symbol'])

    # Sort
    # Define categorical sort order for tiers
    tier_order = ['High_Anisotropy_Adequate_Confidence', 'High_Anisotropy_Low_Confidence', 'Comparator_Panel']
    final_df['Tier_Rank'] = final_df['Confidence_Tier'].apply(lambda x: tier_order.index(x))

    final_df = final_df.sort_values(by=['Tier_Rank', 'anisotropy_index'], ascending=[True, False])

    # Drop the temporary sort column
    final_df = final_df.drop(columns=['Tier_Rank'])

    # Save
    out_path = Path('outputs/afcc/confidence_weighted_ranking.csv')
    out_path.parent.mkdir(parents=True, exist_ok=True)
    final_df.to_csv(out_path, index=False)
    print(f"Saved ranking to {out_path}")

    # Generate Markdown Report
    report_path = Path('reports/confidence_weighted_structural_evidence.md')
    date_str = datetime.now().strftime("%Y-%m-%d")

    report_content = [
        "# Confidence-Weighted Structural Evidence\n",
        f"**Date Generated:** {date_str}",
        f"**Source Data:** `{metrics_file_path}`",
        f"**Generated By:** `scripts/analysis/confidence_weighted_ranking.py`\n",
        "## Overview",
        "This report re-ranks structural candidates based on both their geometric anisotropy and their structural confidence (pLDDT). By weighting high-confidence predictions more heavily, we filter out speculative geometric claims driven by disordered regions.\n",
        "### High-Anisotropy + Adequate-Confidence (Strong Signal)",
        "| Gene | Anisotropy | pLDDT | PAE Blockiness | Morphology |",
        "|------|------------|-------|----------------|------------|"
    ]

    for _, row in high_conf.iterrows():
        report_content.append(f"| {row['gene_symbol']} | {row['anisotropy_index']:.2f} | {row['pLDDT_mean']:.1f} | {row.get('PAE_domain_blockiness_score', 0.0):.2f} | {row['morphology']} |")

    report_content.extend([
        "\n### High-Anisotropy + Low-Confidence (Exploratory Only)",
        "| Gene | Anisotropy | pLDDT | PAE Blockiness | Morphology |",
        "|------|------------|-------|----------------|------------|"
    ])

    for _, row in low_conf.iterrows():
        report_content.append(f"| {row['gene_symbol']} | {row['anisotropy_index']:.2f} | {row['pLDDT_mean']:.1f} | {row.get('PAE_domain_blockiness_score', 0.0):.2f} | {row['morphology']} |")

    report_content.extend([
        "\n## LBX1 Comparator Analysis",
        "The Biological Countercurvature hypothesis posits LBX1 as a key structural or mechanosensitive mediator. However, comparison against a panel of established mechanosensors and low-confidence structures highlights weakness in relying purely on its AlphaFold geometry:\n",
        "| Gene | Anisotropy | pLDDT | PAE Blockiness | Role / Category |",
        "|------|------------|-------|----------------|-----------------|"
    ])

    # Custom annotations for the panel
    roles = {
        'LBX1': '**Spinal interneuron (Low Conf)**',
        'PIEZO2': 'Mechanosensor (Adequate Conf)',
        'LMNA': 'Nuclear mechanosensor (Adequate Conf)',
        'ADGRG6': 'G-protein mechanosensor (Adequate Conf)',
        'RUNX3': 'Transcription factor (Low Conf)',
        'POC5': 'Centriolar/Ciliary (Low Conf)',
        'GHR': 'Growth sensor (Low Conf)'
    }

    for gene in ['LBX1', 'PIEZO2', 'LMNA', 'ADGRG6', 'RUNX3', 'POC5', 'GHR']:
        if gene in panel_df['gene_symbol'].values:
            row = panel_df[panel_df['gene_symbol'] == gene].iloc[0]
            gene_display = f"**{gene}**" if gene == 'LBX1' else gene
            pae = row.get('PAE_domain_blockiness_score', 0.0)
            pae_str = f"{pae:.2f}" if not pd.isna(pae) else "-"
            report_content.append(f"| {gene_display} | {row['anisotropy_index']:.2f} | {row['pLDDT_mean']:.1f} | {pae_str} | {roles.get(gene, '')} |")

    report_content.extend([
        "\n### Findings",
        "1. **LBX1 lacks structural robustness**: Compared to robust mechanosensors like PIEZO2, ADGRG6, and LMNA, LBX1 exhibits low overall confidence (pLDDT=66.9) and intermediate anisotropy (2.27). Its high PAE blockiness (7.35) suggests modular domain architecture rather than a cohesive mechanical rod.",
        "2. **Comparable to other low-confidence factors**: LBX1's profile is closer to other loosely structured transcription factors (RUNX3) than to bona fide mechanosensors.",
        "3. **High-anisotropy is driven by disorder**: Similar to POC5 and GHR, which show extreme anisotropy driven by long, low-confidence extended tails, structural inferences on LBX1 based purely on AF metrics should be treated as speculative and hypothesis-generating only."
    ])

    with open(report_path, 'w') as f:
        f.write("\n".join(report_content) + "\n")

    print(f"Generated Markdown report at {report_path}")

if __name__ == '__main__':
    main()
