import os
import pandas as pd
from pathlib import Path
from collections import defaultdict
import glob
import sys

def run_audit():
    afcc_dir = Path("outputs/afcc")
    reports_dir = Path("reports")

    # 1. Audit run history for reused metrics
    metrics_files = sorted(afcc_dir.glob("*/metrics.csv"))

    gene_history = defaultdict(list)
    run_dates = []
    missing_outputs = []
    schema_drifts = []

    canonical_columns = None

    for mf in metrics_files:
        run_date = mf.parent.name
        run_dates.append(run_date)

        # Check missing linked outputs (e.g. summary.md)
        summary_file = mf.parent / "summary.md"
        if not summary_file.exists():
            missing_outputs.append(f"{run_date}: Missing summary.md")

        try:
            df = pd.read_csv(mf)
        except Exception as e:
            continue

        # Handle schema drift
        if canonical_columns is None:
            canonical_columns = set(df.columns)
            # Handle the specific memory caveat: "Gene" vs "gene_symbol"
            if "Gene" in df.columns:
                df = df.rename(columns={"Gene": "gene_symbol"})
            canonical_columns = set(df.columns)
        else:
            current_columns = set(df.columns)
            if "Gene" in current_columns:
                df = df.rename(columns={"Gene": "gene_symbol"})
                current_columns = set(df.columns)
                schema_drifts.append(f"{run_date}: Older schema (Gene -> gene_symbol)")

            diff = canonical_columns.symmetric_difference(current_columns)
            if diff:
                schema_drifts.append(f"{run_date}: Schema diff {diff}")

        if "gene_symbol" not in df.columns:
            continue

        for _, row in df.iterrows():
            gene = row["gene_symbol"]
            metrics = {
                "anisotropy": row.get("anisotropy_index", 0),
                "plddt": row.get("plddt_mean", 0),
                "pae": row.get("PAE_domain_blockiness_score", 0)
            }
            gene_history[gene].append({"date": run_date, "metrics": metrics})

    identical_vectors = []
    for gene, history in gene_history.items():
        if len(history) > 1:
            first_metrics = history[0]["metrics"]
            is_static = all(h["metrics"] == first_metrics for h in history)
            if is_static:
                identical_vectors.append(gene)

    # Generate report
    report = f"""# Evidence Freshness Audit
*Generated by scripts/analysis/evidence_freshness_audit.py*

## Audit Scope
- Directory: `outputs/afcc/`
- Runs analyzed: {len(metrics_files)}
- Date range: {run_dates[0] if run_dates else 'N/A'} to {run_dates[-1] if run_dates else 'N/A'}

## Identical Per-Gene Vectors Across Runs
The following genes have completely static metrics (anisotropy, pLDDT, PAE blockiness) across all evaluated runs:
{', '.join(identical_vectors) if identical_vectors else 'None'}

*Implication:* Narrative "updates" or newly generated hypotheses based on these static vectors are likely over-interpreting unchanged baseline AlphaFold predictions.

## Missing Linked Outputs
{chr(10).join(f"- {msg}" for msg in missing_outputs) if missing_outputs else "None detected."}

## Schema Drifts Detected
{chr(10).join(f"- {msg}" for msg in schema_drifts) if schema_drifts else "None detected."}

## Recommendations
- Enforce caching rules: explicitly label when data is cached vs re-computed.
- Implement automated checks that fail if a "new" report is generated from identical input vectors without explicitly stating it is a re-analysis.
"""
    with open(reports_dir / "evidence_freshness_audit.md", "w") as f:
        f.write(report)

    print("Audit completed. Report saved to reports/evidence_freshness_audit.md")

if __name__ == "__main__":
    run_audit()
