#!/bin/bash
# Autonomous Script Generated by Jules to fulfill High-Impact Journal requirements
# This script uses the paperbanana CLI to generate three critical artifacts:
# 1. Complex Mechanism: The Derivative Gain Trap
# 2. Key Result: Thermodynamic Stability Phase Diagram
# 3. Visual Abstract: Metabolic Buckling

set -e

# Ensure output directories exist
mkdir -p research/figures/

echo "=== High-Impact Visualization Pipeline ==="

# 1. Complex Mechanism
paperbanana generate --input research/figures/jules_mechanism_derivative_gain_trap.txt --caption 'The Derivative Gain Trap' --output research/figures/jules_autonomous_mechanism_derivative_gain_trap.png

# 2. Key Result
paperbanana plot --data outputs/thermodynamic_cost/phase_diagram_energy_deficit_for_plot.csv --x L --y chi_kappa --color R_deficit --output research/figures/jules_autonomous_thermodynamic_phase_diagram.png

# 3. Visual Abstract
paperbanana generate --input research/figures/jules_visual_abstract_metabolic_buckling.txt --caption 'Visual Abstract: Metabolic Buckling' --output research/figures/jules_autonomous_visual_abstract_metabolic_buckling.png

echo "Pipeline complete."
