#!/bin/bash
# scripts/generate_jules_autonomous_artifacts.sh
#
# Autonomous Script Generated by Jules for High-Impact Visuals
# This script uses the paperbanana CLI to generate three critical artifacts:
# 1. Complex Mechanism: IEC Feedback Loop and Demand-Supply Gap
# 2. Key Result: Thermodynamic Phase Diagram
# 3. Visual Abstract: Biological Countercurvature of Spacetime

# Ensure output directories exist
mkdir -p research/figures/

# 1. Complex Mechanism Diagram: IEC Feedback Loop
echo "Generating Mechanogenetic Feedback Loop Diagram..."
paperbanana generate --input research/figures/jules_synthesized_mechanism.txt --caption 'IEC Feedback Loop and Mechanogenetic Demand-Supply Gap' --output research/figures/jules_synthesized_mechanism.png

# 2. Key Result Plot: Thermodynamic Phase Diagram
echo "Plotting Thermodynamic Phase Diagram..."
paperbanana plot --data outputs/thermodynamic_cost/phase_diagram_energy_deficit_for_plot.csv --intent 'Plot a heatmap mapping L (Spinal Length) to the X-axis, chi_kappa (Coupling Strength) to the Y-axis, and R_deficit (Energy Deficit Ratio) as the color intensity. Use the viridis colormap and draw a red dashed line at the R=1 instability limit. Label axes clearly. Use default fonts.' --output research/figures/jules_synthesized_phase_diagram.png

# 3. Visual Abstract Diagram: Biological Countercurvature of Spacetime
echo "Generating Visual Abstract..."
paperbanana generate --input research/figures/jules_synthesized_visual_abstract.txt --caption 'Visual Abstract: Biological Countercurvature of Spacetime' --output research/figures/jules_synthesized_visual_abstract.png

echo "Pipeline complete. Visual artifacts saved to research/figures/"
