"""
Plot AlphaFold Analysis Results for Manuscript
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
from pathlib import Path
import numpy as np
from scipy.stats import pearsonr

def load_data(csv_file):
    return pd.read_csv(csv_file)

def plot_correlations(df, output_dir):
    """Plot entropy vs curvature correlations"""
    output_dir.mkdir(parents=True, exist_ok=True)

    # Entropy vs Curvature
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x='seq_entropy', y='mean_curvature', hue='category', alpha=0.7)

    # Fit line
    if len(df) > 1:
        z = np.polyfit(df['seq_entropy'], df['mean_curvature'], 1)
        p = np.poly1d(z)
        plt.plot(df['seq_entropy'], p(df['seq_entropy']), "r--", alpha=0.5)

    plt.xlabel('Sequence Entropy (bits)')
    plt.ylabel('Mean Backbone Curvature')
    plt.title('Sequence Information vs. Structural Curvature')
    plt.savefig(output_dir / 'fig_alphafold_correlation.pdf')
    plt.savefig(output_dir / 'fig_alphafold_correlation.png', dpi=300)
    plt.close()

def plot_category_comparison(df, output_dir):
    """Plot boxplots comparing categories"""
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x='category', y='mean_curvature')
    plt.xticks(rotation=45)
    plt.title('Backbone Curvature by Protein Category')
    plt.tight_layout()
    plt.savefig(output_dir / 'fig_alphafold_categories.pdf')
    plt.savefig(output_dir / 'fig_alphafold_categories.png', dpi=300)
    plt.close()

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", required=True, help="Path to analysis CSV")
    parser.add_argument("--summary", required=True, help="Path to summary JSON")
    args = parser.parse_args()

    data_path = Path(args.data)
    summary_path = Path(args.summary)

    # Since alphafold_analyze.py creates bcc_stats_summary.csv (renamed from json suffix),
    # but the Makefile calls it bcc_analysis_data.csv in the alphafold-figs target?
    # Wait, in the Makefile:
    # $(PYTHON) figures/src/plot_alphafold_main.py --data results/bcc_analysis_data.csv --summary results/bcc_stats_summary.json

    # In my modified analyze_bcc_structures.py:
    # csv_output = json_output.with_suffix('.csv')
    # So if json_output is results/bcc_stats_summary.json, then csv is results/bcc_stats_summary.csv

    # But the Makefile expects results/bcc_analysis_data.csv
    # I should align them.

    if not data_path.exists():
        # Try finding the CSV generated by analyze script
        alt_path = summary_path.with_suffix('.csv')
        if alt_path.exists():
            print(f"⚠️ {data_path} not found, using {alt_path}")
            data_path = alt_path
        else:
             print(f"❌ Data file not found: {data_path}")
             return

    print(f"📊 Plotting AlphaFold results from {data_path}")
    df = pd.read_csv(data_path)

    # Add category information if missing
    # In build_dataset.py I added category. But analyze_bcc_structures.py doesn't seem to preserve it from the index CSV
    # because it doesn't read the index CSV! It reads PDB files directly.
    # So I need to add category info back.

    # Load protein database to map names to categories
    try:
        from alphafold_analysis.bcc_protein_database import BCC_PROTEINS
    except ImportError:
        import sys
        sys.path.append('alphafold_analysis')
        try:
            from bcc_protein_database import BCC_PROTEINS
        except ImportError:
            BCC_PROTEINS = {}

    name_to_cat = {}
    for cat, proteins in BCC_PROTEINS.items():
        for name in proteins:
            name_to_cat[name] = cat

    if 'category' not in df.columns:
        df['category'] = df['name'].map(name_to_cat)

    print(f"Mapped {df['category'].notna().sum()}/{len(df)} proteins to categories")
    if df['category'].notna().sum() == 0:
        print("Sample names in CSV:", df['name'].head().tolist())
        print("Sample names in DB:", list(name_to_cat.keys())[:5])

    # Drop rows without category
    df = df.dropna(subset=['category'])

    if len(df) == 0:
        print("❌ No data to plot after filtering categories")
        return

    output_dir = Path("figures/main")
    plot_correlations(df, output_dir)
    plot_category_comparison(df, output_dir)

    print("✅ Figures generated")

if __name__ == "__main__":
    main()
